### ISSUE TITLE
Object 'hyperShadePanel1Window' not found

### ISSUE THREAD

**Issue by Redcroft** [DavideAlidosi/May9#2]
Hi,
Really enjoying using May9, makes Maya feel fresh and enjoyable to use. However i have another slight issue. When i select a node in the hypershade and press 1/2/3 to change visible I/O nothing happens and i get the following issue

// Error: file: /usr/autodesk/maya2017/scripts/startup/defaultRunTimeCommands.mel line 17294: Object 'hyperShadePanel1Window' not found. //

**Comment by DavideAlidosi** [comment]
Hi again,
I really appreciate you like May9 :), TNX.
This issue is probably is related to Layout structure, because in Maya 2017 are deprecated, and the only solution is using the Workspace instead.
Please try 1.1.3 Git build, you find the editor stacked in the bottom of the viewport, they can be open by click on tab and closed by click again on the active tab.

**Comment by Redcroft** [comment]
Hi,
latest git worked a treat, really like the tabs at the bottom. Shame that 2017 breaks layout structure.
Thank you,
